import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "../globals.css";
import Header from "@/components/layout/Header";
import { SanityLive } from "@/sanity/lib/live";
import { getAllCategories } from "@/sanity/lib/products/getAllCategories";
import Footer from "@/components/layout/Footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const categories = await getAllCategories();

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased dark bg-[#131313] flex flex-col min-h-screen `}
      >
        {/* todo body background rengini degistir bg-[#131313] */}
        <Header categories={categories} />
        <main className="flex-1">{children}</main>
        <SanityLive />
        <Footer />
      </body>
    </html>
  );
}
